# Generated by Django 2.1.4 on 2019-05-13 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190103_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 21, 13, 47, 21130)),
        ),
    ]
