# Generated by Django 2.0.9 on 2019-06-10 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190609_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 22, 46, 40, 71616)),
        ),
    ]
